export const ordersData = [
  {
    id: "ORD001",
    customer: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    product: "Laptop Pro 15",
    category: "Electronics",
    quantity: 1,
    price: 75999,
    status: "delivered",
    date: "2025-01-10",
    address: "12 MG Road, Bangalore, Karnataka",
  },
  {
    id: "ORD002",
    customer: "Priya Nair",
    email: "priya.nair@example.com",
    product: "Wireless Headphones",
    category: "Electronics",
    quantity: 2,
    price: 4999,
    status: "delivered",
    date: "2025-01-12",
    address: "45 Anna Salai, Chennai, Tamil Nadu",
  },
  {
    id: "ORD003",
    customer: "Rohan Mehta",
    email: "rohan.mehta@example.com",
    product: "Running Shoes",
    category: "Sports",
    quantity: 1,
    price: 3599,
    status: "cancelled",
    date: "2025-01-15",
    address: "78 FC Road, Pune, Maharashtra",
  },
  {
    id: "ORD004",
    customer: "Sneha Iyer",
    email: "sneha.iyer@example.com",
    product: "Yoga Mat",
    category: "Sports",
    quantity: 3,
    price: 1299,
    status: "delivered",
    date: "2025-01-18",
    address: "23 Park Street, Kolkata, West Bengal",
  },
  {
    id: "ORD005",
    customer: "Vikram Patel",
    email: "vikram.patel@example.com",
    product: "Smart Watch",
    category: "Electronics",
    quantity: 1,
    price: 12999,
    status: "pending",
    date: "2025-01-20",
    address: "56 SG Highway, Ahmedabad, Gujarat",
  },
  {
    id: "ORD006",
    customer: "Anjali Singh",
    email: "anjali.singh@example.com",
    product: "Cotton Kurta Set",
    category: "Clothing",
    quantity: 2,
    price: 2499,
    status: "delivered",
    date: "2025-01-22",
    address: "34 Hazratganj, Lucknow, UP",
  },
  {
    id: "ORD007",
    customer: "Kiran Reddy",
    email: "kiran.reddy@example.com",
    product: "Coffee Maker",
    category: "Home",
    quantity: 1,
    price: 5499,
    status: "cancelled",
    date: "2025-01-25",
    address: "89 Banjara Hills, Hyderabad, Telangana",
  },
  {
    id: "ORD008",
    customer: "Meena Krishnan",
    email: "meena.k@example.com",
    product: "Formal Blazer",
    category: "Clothing",
    quantity: 1,
    price: 4299,
    status: "delivered",
    date: "2025-01-27",
    address: "11 Marine Drive, Mumbai, Maharashtra",
  },
  {
    id: "ORD009",
    customer: "Arjun Das",
    email: "arjun.das@example.com",
    product: "Bluetooth Speaker",
    category: "Electronics",
    quantity: 2,
    price: 3299,
    status: "pending",
    date: "2025-01-29",
    address: "67 MG Marg, Gangtok, Sikkim",
  },
  {
    id: "ORD010",
    customer: "Deepa Menon",
    email: "deepa.menon@example.com",
    product: "Air Purifier",
    category: "Home",
    quantity: 1,
    price: 8999,
    status: "delivered",
    date: "2025-02-01",
    address: "22 Connaught Place, Delhi",
  },
  {
    id: "ORD011",
    customer: "Suresh Kumar",
    email: "suresh.k@example.com",
    product: "Protein Powder",
    category: "Sports",
    quantity: 2,
    price: 2199,
    status: "cancelled",
    date: "2025-02-03",
    address: "14 RS Puram, Coimbatore, Tamil Nadu",
  },
  {
    id: "ORD012",
    customer: "Nisha Gupta",
    email: "nisha.g@example.com",
    product: "Ceramic Dinner Set",
    category: "Home",
    quantity: 1,
    price: 3799,
    status: "delivered",
    date: "2025-02-05",
    address: "99 Civil Lines, Jaipur, Rajasthan",
  },
  {
    id: "ORD013",
    customer: "Rahul Bose",
    email: "rahul.bose@example.com",
    product: "Denim Jeans",
    category: "Clothing",
    quantity: 3,
    price: 1999,
    status: "delivered",
    date: "2025-02-07",
    address: "55 Salt Lake, Kolkata, West Bengal",
  },
  {
    id: "ORD014",
    customer: "Pooja Verma",
    email: "pooja.v@example.com",
    product: "Tablet 10 inch",
    category: "Electronics",
    quantity: 1,
    price: 22999,
    status: "pending",
    date: "2025-02-10",
    address: "31 Sector 17, Chandigarh",
  },
  {
    id: "ORD015",
    customer: "Manoj Pillai",
    email: "manoj.p@example.com",
    product: "Garden Tools Set",
    category: "Home",
    quantity: 1,
    price: 2899,
    status: "cancelled",
    date: "2025-02-12",
    address: "8 Pattom, Thiruvananthapuram, Kerala",
  },
  {
    id: "ORD016",
    customer: "Ritu Agarwal",
    email: "ritu.a@example.com",
    product: "Winter Jacket",
    category: "Clothing",
    quantity: 1,
    price: 5999,
    status: "delivered",
    date: "2025-02-14",
    address: "43 Rajpur Road, Dehradun, Uttarakhand",
  },
  {
    id: "ORD017",
    customer: "Ganesh Rao",
    email: "ganesh.r@example.com",
    product: "Cycling Helmet",
    category: "Sports",
    quantity: 1,
    price: 1799,
    status: "delivered",
    date: "2025-02-16",
    address: "77 Jayanagar, Bangalore, Karnataka",
  },
  {
    id: "ORD018",
    customer: "Lakshmi Naidu",
    email: "lakshmi.n@example.com",
    product: "Mixer Grinder",
    category: "Home",
    quantity: 1,
    price: 4599,
    status: "cancelled",
    date: "2025-02-18",
    address: "19 Arundelpet, Guntur, Andhra Pradesh",
  },
  {
    id: "ORD019",
    customer: "Aditya Joshi",
    email: "aditya.j@example.com",
    product: "Noise Cancelling Earbuds",
    category: "Electronics",
    quantity: 2,
    price: 6999,
    status: "delivered",
    date: "2025-02-20",
    address: "62 Koregaon Park, Pune, Maharashtra",
  },
  {
    id: "ORD020",
    customer: "Sunita Choudhary",
    email: "sunita.c@example.com",
    product: "Badminton Racket Set",
    category: "Sports",
    quantity: 1,
    price: 2299,
    status: "delivered",
    date: "2025-02-22",
    address: "25 Boring Road, Patna, Bihar",
  },
  {
    id: "ORD021",
    customer: "Dev Kapoor",
    email: "dev.k@example.com",
    product: "Gaming Mouse",
    category: "Electronics",
    quantity: 1,
    price: 3499,
    status: "pending",
    date: "2025-02-24",
    address: "38 South Extension, Delhi",
  },
  {
    id: "ORD022",
    customer: "Kavya Nambiar",
    email: "kavya.n@example.com",
    product: "Saree Silk",
    category: "Clothing",
    quantity: 2,
    price: 7499,
    status: "delivered",
    date: "2025-02-26",
    address: "50 Calicut Road, Kozhikode, Kerala",
  },
  {
    id: "ORD023",
    customer: "Tushar Bhatt",
    email: "tushar.b@example.com",
    product: "Electric Kettle",
    category: "Home",
    quantity: 1,
    price: 1499,
    status: "cancelled",
    date: "2025-02-28",
    address: "6 Ashram Road, Ahmedabad, Gujarat",
  },
  {
    id: "ORD024",
    customer: "Simran Kaur",
    email: "simran.k@example.com",
    product: "Fitband Pro",
    category: "Electronics",
    quantity: 1,
    price: 4999,
    status: "delivered",
    date: "2025-03-02",
    address: "17 Model Town, Ludhiana, Punjab",
  },
  {
    id: "ORD025",
    customer: "Harish Nair",
    email: "harish.n@example.com",
    product: "Football",
    category: "Sports",
    quantity: 2,
    price: 999,
    status: "delivered",
    date: "2025-03-04",
    address: "29 Vyttila, Kochi, Kerala",
  },
  {
    id: "ORD026",
    customer: "Bhavna Shah",
    email: "bhavna.s@example.com",
    product: "Pressure Cooker",
    category: "Home",
    quantity: 1,
    price: 2199,
    status: "pending",
    date: "2025-03-06",
    address: "41 CG Road, Ahmedabad, Gujarat",
  },
  {
    id: "ORD027",
    customer: "Naveen Tiwari",
    email: "naveen.t@example.com",
    product: "Formal Shirt Pack",
    category: "Clothing",
    quantity: 3,
    price: 1499,
    status: "cancelled",
    date: "2025-03-08",
    address: "73 Indira Nagar, Lucknow, UP",
  },
  {
    id: "ORD028",
    customer: "Geeta Pillai",
    email: "geeta.p@example.com",
    product: "Webcam HD",
    category: "Electronics",
    quantity: 1,
    price: 2799,
    status: "delivered",
    date: "2025-03-10",
    address: "84 Thampanoor, Thiruvananthapuram, Kerala",
  },
  {
    id: "ORD029",
    customer: "Rajesh Pandey",
    email: "rajesh.p@example.com",
    product: "Cricket Bat",
    category: "Sports",
    quantity: 1,
    price: 3199,
    status: "delivered",
    date: "2025-03-12",
    address: "96 Hazratganj, Allahabad, UP",
  },
  {
    id: "ORD030",
    customer: "Ananya Roy",
    email: "ananya.r@example.com",
    product: "Scented Candle Set",
    category: "Home",
    quantity: 2,
    price: 899,
    status: "delivered",
    date: "2025-03-14",
    address: "10 Lake Gardens, Kolkata, West Bengal",
  },
];
